services:
  backend:
    build: ./backend
    environment:
      CORS_ORIGINS: "http://localhost"
    expose:
      - "8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"
