services:
  backend:
    image: blaxel/wiki-nlp-backend:latest
    environment:
      CORS_ORIGINS: "http://localhost"
    volumes:
      - ./data:/data
      - ./index:/index
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    image: blaxel/wiki-nlp-frontend:latest
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
